# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBase():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_validregistration(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(886, 782)
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Sign up\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//a[contains(.,\'Sign up\')]").click()
    assert self.driver.find_element(By.XPATH, "//h1[contains(.,\'Sign up\')]").text == "Sign up"
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Have an account?\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".form-group:nth-child(3) > .form-control")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//button[contains(.,\'Sign up\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset/input").send_keys("TesterB71011")
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[2]/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[2]/input").send_keys("70111testerbuggie@gmail.com")
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[3]/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[3]/input").send_keys("123ABCabc#&@{}í")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Sign up\')]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-title").text == "Welcome!"
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-text").text == "Your registration was successful!"
    self.driver.find_element(By.XPATH, "//button[contains(.,\'OK\')]").click()
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'TesterB71011\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\' Log out\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Sign in\')]")
    assert len(elements) == 0
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Sign up\')]")
    assert len(elements) == 0
  
