# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAlternate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginwithemptyform(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(886, 782)
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Sign in\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//a[contains(.,\'Sign in\')]").click()
    assert self.driver.find_element(By.XPATH, "//h1[contains(.,\'Sign in\')]").text == "Sign in"
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Need an account?\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'text\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'password\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//button[contains(.,\'Sign in\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'password\']").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Sign in\')]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-title").text == "Login failed!"
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-text").text == "Email field required."
    self.driver.find_element(By.XPATH, "//button[contains(.,\'OK\')]").click()
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'text\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'password\']")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "conduit").click()
  
  def test_loginwithaninvalidemailaddress(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(886, 782)
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Sign in\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//a[contains(.,\'Sign in\')]").click()
    assert self.driver.find_element(By.XPATH, "//h1[contains(.,\'Sign in\')]").text == "Sign in"
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Need an account?\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'text\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'password\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//button[contains(.,\'Sign in\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").send_keys("lajcsikagmail.com")
    self.driver.find_element(By.XPATH, "//input[@type=\'password\']").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'password\']").send_keys("123ABCabc#&@{}í")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Sign in\')]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-title").text == "Login failed!"
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-text").text == "Email must be a valid email."
    self.driver.find_element(By.XPATH, "//button[contains(.,\'OK\')]").click()
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'text\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'password\']")
    assert len(elements) > 0
    value = self.driver.find_element(By.XPATH, "//input[@type=\'text\']").get_attribute("value")
    assert value == "lajcsikagmail.com"
    value = self.driver.find_element(By.XPATH, "//input[@type=\'password\']").get_attribute("value")
    assert value == "123ABCabc#&@{}í"
    self.driver.find_element(By.LINK_TEXT, "conduit").click()
  
  def test_loginwithnonexistinguser(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(886, 782)
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Sign in\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//a[contains(.,\'Sign in\')]").click()
    assert self.driver.find_element(By.XPATH, "//h1[contains(.,\'Sign in\')]").text == "Sign in"
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Need an account?\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'text\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'password\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//button[contains(.,\'Sign in\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").send_keys("lajcsika@gmail.com")
    self.driver.find_element(By.XPATH, "//input[@type=\'password\']").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'password\']").send_keys("123ABCabc#&@{}í")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Sign in\')]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-title").text == "Login failed!"
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-text").text == "Invalid user credentials."
    self.driver.find_element(By.XPATH, "//button[contains(.,\'OK\')]").click()
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'text\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'password\']")
    assert len(elements) > 0
    value = self.driver.find_element(By.XPATH, "//input[@type=\'text\']").get_attribute("value")
    assert value == "lajcsika@gmail.com"
    value = self.driver.find_element(By.XPATH, "//input[@type=\'password\']").get_attribute("value")
    assert value == "123ABCabc#&@{}í"
    self.driver.find_element(By.LINK_TEXT, "conduit").click()
  
  def test_loginwithaninvalidpassword(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(886, 782)
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Sign in\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//a[contains(.,\'Sign in\')]").click()
    assert self.driver.find_element(By.XPATH, "//h1[contains(.,\'Sign in\')]").text == "Sign in"
    elements = self.driver.find_elements(By.XPATH, "//a[contains(.,\'Need an account?\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'text\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'password\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//button[contains(.,\'Sign in\')]")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").send_keys("chesterbuggie@gmail.com")
    self.driver.find_element(By.XPATH, "//input[@type=\'password\']").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'password\']").send_keys("76AsdjdjdB")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Sign in\')]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-title").text == "Login failed!"
    assert self.driver.find_element(By.CSS_SELECTOR, ".swal-text").text == "Invalid user credentials."
    self.driver.find_element(By.XPATH, "//button[contains(.,\'OK\')]").click()
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'text\']")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//input[@type=\'password\']")
    assert len(elements) > 0
    value = self.driver.find_element(By.XPATH, "//input[@type=\'text\']").get_attribute("value")
    assert value == "chesterbuggie@gmail.com"
    value = self.driver.find_element(By.XPATH, "//input[@type=\'password\']").get_attribute("value")
    assert value == "76AsdjdjdB"
    self.driver.find_element(By.LINK_TEXT, "conduit").click()
  
